// Code generated by MockGen. DO NOT EDIT.
// Source: ./business/analytics/analytics.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/business/analytics/mock_analytics.go -package=analytics -source=./business/analytics/analytics.go
//

// Package analytics is a generated GoMock package.
package analytics
