version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "whatsapp "
      include: scope
    labels:
      - maintenance
      - dependencies
  - package-ecosystem: gomod
    directory: /_examples
    schedule:
      interval: daily
    commit-message:
      prefix: "examples"
      include: scope
    labels:
      - maintenance
      - dependencies
  - package-ecosystem: gomod
    directory: /extras/otel
    schedule:
      interval: daily
    commit-message:
      prefix: "extras otel "
      include: scope
    labels:
      - maintenance
      - dependencies
