version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "whatsapp "
          include: "scope"
      labels:
          - "maintenance"
          - "dependencies"
      groups:
          go-root-modules:
              patterns:
                  - "*"

    - package-ecosystem: "gomod"
      directory: "/_examples"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "examples"
          include: "scope"
      labels:
          - "maintenance"
          - "dependencies"
      groups:
          go-examples:
              patterns:
                  - "*"

    - package-ecosystem: "gomod"
      directory: "/extras/otel"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "extras otel "
          include: "scope"
      labels:
          - "maintenance"
          - "dependencies"
      groups:
          go-extras-otel:
              patterns:
                  - "*"

    - package-ecosystem: "gomod"
      directory: "/extras/mcp"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "extras mcp "
          include: "scope"
      labels:
          - "maintenance"
          - "dependencies"
      groups:
          go-extras-mcp:
              patterns:
                  - "*"
