// Code generated by MockGen. DO NOT EDIT.
// Source: ./qrcode/qrcode.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/qrcode/mock_qrcode.go -package=qrcode -source=./qrcode/qrcode.go
//

// Package qrcode is a generated GoMock package.
package qrcode
