linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/piusalfred/whatsapp) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
    no-inline-comments: true
    no-prefix-comments: true
    skip-generated: true
    funlen:
    lines: 70
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 45
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - funlen
        - goerr113
        - gocognit
        - dupl
        - gosec
        - lll
  exclude-dirs:
    - examples
    - mocks
linters:
  # enable all available linters
  enable-all: true
  # enable some additional linters that are not enabled by default
  disable:
    - funlen
    - cyclop
    - testpackage
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - wsl
    - mnd
    - tagliatelle
    - musttag
    - exhaustruct
    - wastedassign
    - dupword
    - varnamelen
    - depguard
    - forbidigo
    - ireturn

output:
  formats:
    - format: colored-line-number
      path: stdout
  sort-results: true
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.
  show-stats: true
run:
  go: '1.23'
  concurrency: 5
  timeout: 5m