// Code generated by MockGen. DO NOT EDIT.
// Source: ./phonenumber/phonenumber.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/phonenumber/mock_phonenumber.go -package=phonenumber -source=./phonenumber/phonenumber.go
//

// Package phonenumber is a generated GoMock package.
package phonenumber
