// Code generated by MockGen. DO NOT EDIT.
// Source: ./conversation/automation/automation.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/conversation/automation/mock_automation.go -package=automation -source=./conversation/automation/automation.go
//

// Package automation is a generated GoMock package.
package automation
