// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -destination=../mocks/user/mock_user.go -package=user -source=user.go
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	user "github.com/piusalfred/whatsapp/user"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockUsersService is a mock of BlockUsersService interface.
type MockBlockUsersService struct {
	ctrl     *gomock.Controller
	recorder *MockBlockUsersServiceMockRecorder
}

// MockBlockUsersServiceMockRecorder is the mock recorder for MockBlockUsersService.
type MockBlockUsersServiceMockRecorder struct {
	mock *MockBlockUsersService
}

// NewMockBlockUsersService creates a new mock instance.
func NewMockBlockUsersService(ctrl *gomock.Controller) *MockBlockUsersService {
	mock := &MockBlockUsersService{ctrl: ctrl}
	mock.recorder = &MockBlockUsersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockUsersService) EXPECT() *MockBlockUsersServiceMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockBlockUsersService) Block(ctx context.Context, numbers []string) (*user.BlockUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, numbers)
	ret0, _ := ret[0].(*user.BlockUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockBlockUsersServiceMockRecorder) Block(ctx, numbers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockBlockUsersService)(nil).Block), ctx, numbers)
}

// ListBlocked mocks base method.
func (m *MockBlockUsersService) ListBlocked(ctx context.Context, request *user.ListBlockedUsersOptions) (*user.GetBlockedUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocked", ctx, request)
	ret0, _ := ret[0].(*user.GetBlockedUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocked indicates an expected call of ListBlocked.
func (mr *MockBlockUsersServiceMockRecorder) ListBlocked(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocked", reflect.TypeOf((*MockBlockUsersService)(nil).ListBlocked), ctx, request)
}

// Unblock mocks base method.
func (m *MockBlockUsersService) Unblock(ctx context.Context, numbers []string) (*user.BlockUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unblock", ctx, numbers)
	ret0, _ := ret[0].(*user.BlockUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unblock indicates an expected call of Unblock.
func (mr *MockBlockUsersServiceMockRecorder) Unblock(ctx, numbers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unblock", reflect.TypeOf((*MockBlockUsersService)(nil).Unblock), ctx, numbers)
}
