// Code generated by MockGen. DO NOT EDIT.
// Source: ./webhooks/handler.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/webhooks/mock_webhooks_handlers.go -package=webhooks -source=./webhooks/handler.go
//

// Package webhooks is a generated GoMock package.
package webhooks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler[S any, T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder[S, T]
	isgomock struct{}
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder[S any, T any] struct {
	mock *MockEventHandler[S, T]
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler[S any, T any](ctrl *gomock.Controller) *MockEventHandler[S, T] {
	mock := &MockEventHandler[S, T]{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder[S, T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler[S, T]) EXPECT() *MockEventHandlerMockRecorder[S, T] {
	return m.recorder
}

// HandleEvent mocks base method.
func (m *MockEventHandler[S, T]) HandleEvent(ctx context.Context, ntx *S, notification *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleEvent", ctx, ntx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleEvent indicates an expected call of HandleEvent.
func (mr *MockEventHandlerMockRecorder[S, T]) HandleEvent(ctx, ntx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockEventHandler[S, T])(nil).HandleEvent), ctx, ntx, notification)
}
