// Code generated by MockGen. DO NOT EDIT.
// Source: ./webhooks/handler.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/webhooks/mock_webhooks_handlers.go -package=webhooks -source=./webhooks/handler.go
//

// Package webhooks is a generated GoMock package.
package webhooks

import (
	context "context"
	reflect "reflect"

	webhooks "github.com/piusalfred/whatsapp/webhooks"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowEventHandler is a mock of FlowEventHandler interface.
type MockFlowEventHandler[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockFlowEventHandlerMockRecorder[T]
	isgomock struct{}
}

// MockFlowEventHandlerMockRecorder is the mock recorder for MockFlowEventHandler.
type MockFlowEventHandlerMockRecorder[T any] struct {
	mock *MockFlowEventHandler[T]
}

// NewMockFlowEventHandler creates a new mock instance.
func NewMockFlowEventHandler[T any](ctrl *gomock.Controller) *MockFlowEventHandler[T] {
	mock := &MockFlowEventHandler[T]{ctrl: ctrl}
	mock.recorder = &MockFlowEventHandlerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowEventHandler[T]) EXPECT() *MockFlowEventHandlerMockRecorder[T] {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFlowEventHandler[T]) Handle(ctx context.Context, req *webhooks.FlowRequest[T]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockFlowEventHandlerMockRecorder[T]) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFlowEventHandler[T])(nil).Handle), ctx, req)
}
