// Code generated by MockGen. DO NOT EDIT.
// Source: ./message/status.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/message/mock_status_update.go -package=message -source=./message/status.go
//

// Package message is a generated GoMock package.
package message

import (
	context "context"
	reflect "reflect"

	message "github.com/piusalfred/whatsapp/message"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusUpdater is a mock of StatusUpdater interface.
type MockStatusUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockStatusUpdaterMockRecorder
	isgomock struct{}
}

// MockStatusUpdaterMockRecorder is the mock recorder for MockStatusUpdater.
type MockStatusUpdaterMockRecorder struct {
	mock *MockStatusUpdater
}

// NewMockStatusUpdater creates a new mock instance.
func NewMockStatusUpdater(ctrl *gomock.Controller) *MockStatusUpdater {
	mock := &MockStatusUpdater{ctrl: ctrl}
	mock.recorder = &MockStatusUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusUpdater) EXPECT() *MockStatusUpdaterMockRecorder {
	return m.recorder
}

// UpdateStatus mocks base method.
func (m *MockStatusUpdater) UpdateStatus(ctx context.Context, request *message.StatusUpdateRequest) (*message.StatusUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, request)
	ret0, _ := ret[0].(*message.StatusUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockStatusUpdaterMockRecorder) UpdateStatus(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockStatusUpdater)(nil).UpdateStatus), ctx, request)
}
