// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/http/http.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/http/mock_http.go -package=http -source=./pkg/http/http.go
//

// Package http is a generated GoMock package.
package http

import (
	context "context"
	reflect "reflect"

	http "github.com/piusalfred/whatsapp/pkg/http"
	gomock "go.uber.org/mock/gomock"
)

// MockCoreClientOption is a mock of CoreClientOption interface.
type MockCoreClientOption[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockCoreClientOptionMockRecorder[T]
	isgomock struct{}
}

// MockCoreClientOptionMockRecorder is the mock recorder for MockCoreClientOption.
type MockCoreClientOptionMockRecorder[T any] struct {
	mock *MockCoreClientOption[T]
}

// NewMockCoreClientOption creates a new mock instance.
func NewMockCoreClientOption[T any](ctrl *gomock.Controller) *MockCoreClientOption[T] {
	mock := &MockCoreClientOption[T]{ctrl: ctrl}
	mock.recorder = &MockCoreClientOptionMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreClientOption[T]) EXPECT() *MockCoreClientOptionMockRecorder[T] {
	return m.recorder
}

// apply mocks base method.
func (m *MockCoreClientOption[T]) apply(client *http.CoreClient[T]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "apply", client)
}

// apply indicates an expected call of apply.
func (mr *MockCoreClientOptionMockRecorder[T]) apply(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "apply", reflect.TypeOf((*MockCoreClientOption[T])(nil).apply), client)
}

// MockSender is a mock of Sender interface.
type MockSender[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder[T]
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder[T any] struct {
	mock *MockSender[T]
}

// NewMockSender creates a new mock instance.
func NewMockSender[T any](ctrl *gomock.Controller) *MockSender[T] {
	mock := &MockSender[T]{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender[T]) EXPECT() *MockSenderMockRecorder[T] {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender[T]) Send(ctx context.Context, request *http.Request[T], decoder http.ResponseDecoder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, request, decoder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder[T]) Send(ctx, request, decoder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender[T])(nil).Send), ctx, request, decoder)
}
