// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/http/http.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/http/mock_http.go -package=http -source=./pkg/http/http.go
//

// Package http is a generated GoMock package.
package http

import (
	context "context"
	reflect "reflect"

	http "github.com/piusalfred/whatsapp/pkg/http"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder[T]
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder[T any] struct {
	mock *MockSender[T]
}

// NewMockSender creates a new mock instance.
func NewMockSender[T any](ctrl *gomock.Controller) *MockSender[T] {
	mock := &MockSender[T]{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender[T]) EXPECT() *MockSenderMockRecorder[T] {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender[T]) Send(ctx context.Context, request *http.Request[T], decoder http.ResponseDecoder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, request, decoder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder[T]) Send(ctx, request, decoder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender[T])(nil).Send), ctx, request, decoder)
}

// MockCoreSenderOption is a mock of CoreSenderOption interface.
type MockCoreSenderOption struct {
	ctrl     *gomock.Controller
	recorder *MockCoreSenderOptionMockRecorder
	isgomock struct{}
}

// MockCoreSenderOptionMockRecorder is the mock recorder for MockCoreSenderOption.
type MockCoreSenderOptionMockRecorder struct {
	mock *MockCoreSenderOption
}

// NewMockCoreSenderOption creates a new mock instance.
func NewMockCoreSenderOption(ctrl *gomock.Controller) *MockCoreSenderOption {
	mock := &MockCoreSenderOption{ctrl: ctrl}
	mock.recorder = &MockCoreSenderOptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreSenderOption) EXPECT() *MockCoreSenderOptionMockRecorder {
	return m.recorder
}

// apply mocks base method.
func (m *MockCoreSenderOption) apply(client *http.CoreSenderConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "apply", client)
}

// apply indicates an expected call of apply.
func (mr *MockCoreSenderOptionMockRecorder) apply(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "apply", reflect.TypeOf((*MockCoreSenderOption)(nil).apply), client)
}
