name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        go-version:
          - stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Clear Go cache
        run: |
          go clean -modcache
          go clean -cache

      - name: Install gotools
        run: go install github.com/piusalfred/gotools/cmd/gotools@latest
        env:
          GOPROXY: direct

      - name: Download dependencies
        run: go mod download
        env:
          GOPROXY: direct

      - name: Sanity Check
        run: make check

      - name: Test
        run: make test

      - name: Build
        run: go build -v ./...
    
