name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                go-version: ["stable"]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go-version }}
                  cache-dependency-path: |
                      go.sum
                      tools/*.sum

            - name: Install gotools
              run: go install github.com/piusalfred/gotools/cmd/gotools@latest

            - name: Download dependencies
              run: go mod download

            - name: Sanity Check
              run: make check

            - name: Test
              run: make test

            - name: Build
              run: go build -v ./...
